name: "FoD MAST Scan"
description: "Runs a Fortify on Demand Scan of a Mobile application"
inputs:
  working-directory:
    required: false
    description: "Relative directory (from root of repository) from where to run commands"
    default: "./src"
  fod-api-url:
    required: false
    description: "FoD API URI"
    default: "https://ams.fortify.com"
  fod-client-id:
    required: true
    description: "FoD API Client Id"
  fod-client-secret:
    required: true
    description: "FoD API Client Secret"
  fod-app-name:
    required: true
    description: "FoD Application Name"
  fod-release-name:
    required: true
    description: "FoD Release Name"
  fod-parent-release-name:
    required: false
    description: "FoD Parent Release Name"
    default: "main"
  node_version:
    required: false
    description: "Version of node to use"
    default: "16"
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install appropriate version of Node.Js and project dependencies from npm
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install Dependencies
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        pwd
        npm install --only=prod
        npm install --package-lock-only
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
        sc-client: latest
        fod-uploader: skip
        vuln-exporter: v2
        bugtracker-utility: skip
    # Login to Fortify on Demand fcli session
    - name: Login fcli
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli --version
        fcli fod session login --url $FOD_API_URI --client-id $FOD_CLIENT_ID --client-secret $FOD_CLIENT_SECRET --session github-actions
      env:
        FOD_API_URI: ${{ inputs.fod-api-url }}
        FOD_CLIENT_ID: ${{ inputs.fod-client-id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod-client-secret }}
    # Create a new Fortify on Demand release for GitHub branch
    - name: Create FoD release
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli fod release list --app "$FOD_APP_NAME" --session github-actions
        echo fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions
        RELID=$(fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions)
        echo "::debug::Created FOD_RELEASE_ID=${RELID}"
        echo "FOD_RELEASE_ID=${RELID}" >> $GITHUB_OUTPUT
      id: create_fod_release
      env:
        FOD_APP_NAME: ${{ inputs.fod-app-name }}
        FOD_RELEASE_NAME: ${{ inputs.fod-release-name }}
        FOD_PARENT_RELEASE_NAME: ${{ inputs.fod-parent-release-name }}
    # Build the Android APK
    - name: Build Android Release
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        cd android && sh ./gradlew assembleRelease
    # Start Fortify on Demand MAST scan and wait until results complete.
    - name: Perform MAST scan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli fod mast-scan start --release "${FOD_RELEASE_NAME}" --framework Android --entitlement-frequency Subscription --assessment-type "Mobile Assessment" -f $APK_FILE --store curScan --session github-actions
        sleep 5
        fcli fod mast-scan wait-for ::curScan:: --session github-actions
      id: perform_mobile_scan
      env:
        APK_FILE: "./android/app/build/outputs/apk/release/app-release.apk"
        FOD_RELEASE_NAME: ${{ format('{0}:{1}', inputs.fod-app-name, inputs.fod-release-name) }}
        FOD_SCAN_NOTES: "Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    # Logout/Close Fortify on Demand fcli session
    - name: Logout fcli
      shell: bash
      run: |
        fcli fod session logout --session github-actions        

