name: "Verify FoD Security Policy"
description: "Verify that the security policy in Fortify on Demand has been met for the release"
inputs:
  working-directory:
    required: false
    description: "Relative directory (from root of repository) from where to run commands"
    default: "."
  fod-api-uri:
    required: false
    description: "FoD API URI"
    default: "https://api.emea.fortify.com"
  fod-client-id:
    required: true
    description: "FoD API Client Id"
  fod-client-secret:
    required: true
    description: "FoD API Client Secret"
  fod-app-name:
    required: false
    description: "FoD Application Name"
    default: ${{ github.action_repository }}
  fod-release-name:
    required: false
    description: "FoD Release Name"
    default: ${{ github.action_ref }}
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
        sc-client: latest
        fod-uploader: skip
        vuln-exporter: v2
        bugtracker-utility: skip
    # Login to Fortify on Demand fcli session
    - name: Login fcli
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        fcli --version
        fcli fod session login --url $FOD_API_URI --client-id $FOD_CLIENT_ID --client-secret $FOD_CLIENT_SECRET --session github-actions
      env:
        FOD_API_URI: ${{ inputs.fod-api-uri }}
        FOD_CLIENT_ID: ${{ inputs.fod-client-id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod-client-secret }}
    # Run script to check the Security Policy of the Fortify on Demand Release to determine success/failure
    # We will just print a message in this example
    - name: Verify Security Policy
      shell: bash
      run: |
        fcli fod release get "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" -o expr="Critical:\t{critical}\nHigh:\t\t{high}\nMedium:\t\t{medium}\nLow:\t\t{low}" --session github-actions
        if [ $(fcli fod release get "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" -o expr="{isPassed}" --session github-actions) = 'true' ]; then echo "Security policy: passed"; else echo "Security policy: failed"; fi
      id: verify_security_policy
      env:
        FOD_APP_NAME: ${{ inputs.fod-app-name }}
        FOD_RELEASE_NAME: ${{ inputs.fod-release-name }}
    # Logout/Close Fortify on Demand fcli session
    - name: Logout fcli
      shell: bash
      run: |
        fcli fod session logout --session github-actions        

