name: "FoD App and Release Name"
description: "Set the Fortify on Demand App and Release Name based on branch/PR and overrides"
inputs:
  default_fod_app_name:
    required: true
    description: "Default FoD Application Name"
  default_fod_release_name:
    required: true
    description: "Default FoD Release Name"
  app_name_postfix:
    required: false
    description: "Additional string to append to App Name to make it unique for a user"
    default: ""
outputs:
  app_name:
    description: "FoD Application Name"
    value: ${{ steps.fod-app-name.outputs.app_name }}
  release_name:
    description: "FoD Release Name"
    value: ${{ steps.fod-release-name.outputs.release_name }}
runs:
  using: "composite"
  steps:
    - name: Check Out Source Code
      uses: actions/checkout@v3.3.0
    - name: Get FoD App Name
      id: fod-app-name
      shell: bash
      run: |
        if [[ -z "$APP_NAME_POSTFIX" ]]; then
          echo "::debug::Setting: '$DEFAULT_APP_NAME'"
          echo "$DEFAULT_APP_NAME" >> $GITHUB_OUTPUT
        else
          echo "::debug::Setting: '$OVERRIDE_APP_NAME'"
          echo "$OVERRIDE_APP_NAME" >> $GITHUB_OUTPUT
        fi
      env:
        APP_NAME_POSTFIX: ${{ inputs.app_name_postfix }}
        DEFAULT_APP_NAME: ${{ format('{0}={1}', 'app_name', inputs.default_fod_app_name) }}
        OVERRIDE_APP_NAME: ${{ format('{0}={1} {2}', 'app_name', inputs.default_fod_app_name, inputs.app_name_postfix) }}
    - name: Get FoD Release Name
      id: fod-release-name
      shell: bash
      run: |
        if [[ $GITHUB_REF == *"refs/pull/"* ]]; then
          BRANCH_NAME="$(echo ${GITHUB_REF#refs/pull/})"
          PR_NUMBER="$(echo ${BRANCH_NAME%/merge})"
          BRANCH_NAME="[PR]${SOURCE_BRANCH}#${PR_NUMBER}"
        else
          BRANCH_NAME="$(echo ${GITHUB_REF#refs/heads/})"
        fi
        echo "::debug::release_name=${BRANCH_NAME}"         
        echo "release_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
      env:
        SOURCE_BRANCH: ${{ github.head_ref }}
